### PR TITLE
Added option to create fibrils with an exponential length distribution

### PR DESCRIPTION
**Pull request by H-Cox**
Exponential length distributions are biologically and theoretically relevant and therefore I added an option to have the fibril/image generator use an exponential fibril length distribution. The only parameter that is required is the mean of the distribution, hopefully, what I have added has not affected anything else. I shouldn't think it has.

### CODE REVIEW

**Comment by ivan-usov** [comment]
Thanks, @H-Cox ! Looks good, I have only one quick comment. The exponential distribution doesn't use `sigma` at all. It would be nice to somehow emphasize it, so that users do not get confused. E.g. the edit field for sigma can get disabled (grayed out), when one selects 'Exponential' from the popup menu. What do you think?

**Comment by H-Cox** [comment]
Yeah, that’s a good idea, I’ll have a go at trying to implement that and let you know. Do you have any tips where to start?

Cheers,
Henry

________________________________

**Comment by ivan-usov** [comment]
You can have a look at the code in the same function, where some edit fields are disabled, e.g.:
https://github.com/H-Cox/FiberApp/blob/1b9b2232d053d18d076287c374d7d3ae948ed32d/%2Bpanel/FiberImageGenerator.m#L177-L184
```matlab
function FiberImageGenerator_GenerateImage(hObject, eventdata)
ui = get(get(hObject, 'Parent'), 'UserData');
if get(hObject, 'Value') == get(hObject, 'Max')
    set([ui.imSize, ui.imSize_nm, ui.tipRad, ui.zStep], 'Enable', 'on');
else
    set([ui.imSize, ui.imSize_nm, ui.tipRad, ui.zStep], 'Enable', 'off');
end
end
```
In other words, you can disable `ui.sigma` field via:
```matlab
set(ui.sigma, 'Enable', 'off');
```
Also, the field should be re-enabled once a user selects another option than 'Exponential'

**Comment by ivan-usov** [comment]
Hey, @H-Cox , this should be good now. I'll merge your PR now. Thanks!

**Pull request merged**
